input_stream: "HTTP_REQUEST_PAYLOAD:input"
output_stream: "HTTP_RESPONSE_PAYLOAD:output"

node {
  calculator: "HttpLLMCalculator"
  input_stream: "LOOPBACK:loopback"
  input_stream: "HTTP_REQUEST_PAYLOAD:input"
  output_stream: "LOOPBACK:loopback_out"
  output_stream: "HTTP_RESPONSE_PAYLOAD:output"
  input_side_packet: "LLM_NODE_RESOURCES:llm"
  node_options: {
    [type.googleapis.com/mediapipe.LlmCalculatorOptions] {
      models_path: "/models/tiny-llama-1.1b-chat"
      cache_size: 4
    }
  }
}
